packages:
  - apps/*
  - packages/*
  - scripts/*

ignoredBuiltDependencies:
  - '@prisma/client'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@swc/core'
  - aws-sdk
  - ffmpeg-static
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
